DROP TABLE HAS_OPTIONAL;
DROP TABLE HAS_SPAZI;
DROP TABLE PRENOTAZIONE;
DROP TABLE STANZA;
DROP TABLE AGENZIA;

/* Tables */
CREATE TABLE AGENZIA (
    CodA INTEGER NOT NULL,
    tel INTEGER NOT NULL,
    sito_web VARCHAR(32),
    CAP_indirizzo INTEGER NOT NULL,
    numero_indirizzo INTEGER NOT NULL,
    citta_indirizzo VARCHAR(32) NOT NULL,
    via_indirizzo VARCHAR(32) NOT NULL,
    stato_indirizzo VARCHAR(32) NOT NULL,
    PRIMARY KEY (CodA)
);
CREATE TABLE STANZA (
    CodS INTEGER NOT NULL,
    piano INTEGER NOT NULL,
    superficie INTEGER NOT NULL,
    Type VARCHAR(32) NOT NULL,
    PRIMARY KEY (CodS)
);
CREATE TABLE PRENOTAZIONE (
    STANZA_CodS INTEGER NOT NULL,
    data_inizio VARCHAR(32) NOT NULL,
    data_fine VARCHAR(32) NOT NULL,
    costo INTEGER NOT NULL,
    AGENZIA_CodA INTEGER NOT NULL,
    PRIMARY KEY (STANZA_CodS, data_inizio),
    FOREIGN KEY (STANZA_CodS) REFERENCES STANZA(CodS),
    FOREIGN KEY (AGENZIA_CodA) REFERENCES AGENZIA(CodA)
);
CREATE TABLE HAS_SPAZI (
    SPAZI_spazi VARCHAR(32) NOT NULL,
    STANZA_CodS INTEGER NOT NULL,
    PRIMARY KEY (SPAZI_spazi, STANZA_CodS),
    FOREIGN KEY (STANZA_CodS) REFERENCES STANZA(CodS)
);
CREATE TABLE HAS_OPTIONAL (
    OPTIONAL_optional VARCHAR(32) NOT NULL,
    STANZA_CodS INTEGER NOT NULL,
    PRIMARY KEY (OPTIONAL_optional, STANZA_CodS),
    FOREIGN KEY (STANZA_CodS) REFERENCES STANZA(CodS)
);